services:
  app:
    build: .
    restart: unless-stopped
    environment:
      MONGO_URI: mongodb://mongo:27017/minecraft_server_archive
      PORT: 5200
    volumes:
      - ./.env:/app/.env:ro
      - type: bind
        source: /root/srv/archive/downloads
        target: /app/downloads
        read_only: true
        bind:
          create_host_path: false
    ports:
      - "5200:5200"
    depends_on:
      - mongo

    networks:
      - proxy

    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.myapp.rule=Host(`archive.wouterk12.com`)"
      - "traefik.http.routers.myapp.entrypoints=websecure"
      - "traefik.http.routers.myapp.tls.certresolver=letsencrypt"

      - "traefik.http.services.myapp.loadbalancer.server.port=5200"

  mongo:
    image: mongo:6
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

networks:
  proxy:
    external: true
